version: 2.1
jobs:
  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: Update known hosts
          command: |
            ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
      - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST "mkdir test";
workflows:
  build-test-deploy:
    jobs:
      - deploy